### ISSUE TITLE
Font styles and colors

### ISSUE THREAD

**Issue by Ishmeetkaur36** [Note-Vault/Note-Vault#142]
The font styles and size of the home page looks too basic. The red colored font does'nt blend well with the surroundings.

I would like to sort out this issue

**Comment by goyalh4164** [comment]
@Ishmeetkaur36 put some screenshots where you want to work as some PR are recently merged so the UI is completely updated of Home Page

**Comment by Ishmeetkaur36** [comment]
![Screenshot 2024-05-16 211255](https://github.com/Note-Vault/Note-Vault/assets/164319173/eaf87645-1df2-4ea4-9bab-c60c6df7e5e8)
![Screenshot 2024-05-16 211217](https://github.com/Note-Vault/Note-Vault/assets/164319173/34e98cc7-990a-4f38-84f0-e17d0c4f2726)

I would like to work on the styles of these fonts with some underlining to the header titles under gssoc

**Comment by 143divya** [comment]
Please assign this to me

**Comment by DhayanandhS** [comment]
Hey @Ishmeetkaur36, I can clearly see the font size is too big and color palatte does not match in some sections. 

The problem here is the look of the website play important when a viewer views it, their first impression should be good and great about the color and look. 

I can make changes on the font respectively to the theme of the website. If possible I can also add som effects to it.

Can you please assign this isssue to me?

**Comment by DhayanandhS** [comment]
@Ishmeetkaur36, as of now the landing page looks like this. 

![Screenshot 2024-05-19 193443](https://github.com/Note-Vault/Note-Vault/assets/112493275/de3d2d59-590f-4031-bb63-b00971f2e2d0)

Problem: A bad font size or style on the landing page willl affect the readability, professionalism, user experience and brand repution.

Solution: I can ensure that new font and image are integrated seamlessly into the landing page.

Can you please assign this issue to me? If there is any prioritizing in assigning the issue I can always colaborate with other contributors. Like I'm comfortable to working with @143divya. 

Please consider this
