### ISSUE TITLE
DOC: Adding how to connect to database in readme.md

### ISSUE THREAD

**Issue by Chelseasingla1** [Note-Vault/Note-Vault#60]
### What's wrong with the existing documentation

There is no given statements about how one can connect to the database.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
Please assign me this issue under GSSoC'24

**Comment by VaibhavArora314** [comment]
Sure, go ahead.

**Comment by Chelseasingla1** [comment]
> Sure, go ahead.

okay thanks!!

**Comment by gunner26735** [comment]
Hello @VaibhavArora314, I have seen the issue has been inactive since 1 week. So, I thought I would contribute to it. As it is very necessary to setup monogdb locally before working on the project. If it is not done ASAP then it would create friction for new comers who want to contribute.

please, assign this issue to me.
Thanks

**Comment by VaibhavArora314** [comment]
@Chelseasingla1 are u working on this?
